### ISSUE TITLE
Big number of nested fields

### ISSUE THREAD

**Issue by SergeyKokichev** [marchah/json-mapper-json#12]
Hello.
Sometimes there is a need to get a JSON with a mass of nested fields as a result of mapping like this:
`"query": {
       "constant_score" : {
          "filter" : {
              "bool" : {
                "must" : [
                   { "term" : {"name" : "foo"}},
                   { "term" : {"id": 1}}
                ]
              }
          }
        }
    }`

A source is:
``var source = {
    "data": {
        "terms": [ {"item": "one"}, {"item": "two"} ]
    }
}``

Is there a way to avoid templates like this:
`"query": {
	path: "$root.data",
	nested: {
		"constant_score": {
			path: "$root.data",
			nested: {
				"filter" : {
					path: "$root.data",
					nested: {
						"bool": {
							path: "$root.data",
							nested: {
								"must": {
									path: "$root.data.terms"
								}
							}
						}
					}
				}
			}
		}
	}
}`

**Comment by marchah** [comment]
For result I get that:

```javascript
{
  "query": {
    "constant_score": {
      "filter": {
        "bool": {
          "must": [
            {
              "item": "one"
            },
            {
              "item": "two"
            }
          ]
        }
      }
    }
  }
}
```
Can you correct your template or source to match the result you want please.Will be easier for me to understand what you want.
