### ISSUE TITLE
[Feature request] Support defaultValue

### ISSUE THREAD

**Issue by xcatliu** [marchah/json-mapper-json#16]
Hi, this is an awesome tool to transform data. Thanks for your awesome work!
I am thinking if it's possible to add an option to pass defaultValue to a field. Return the defaultValue rather than throw an error `Invalid path xxx`

**Comment by marchah** [comment]
Hi,

Thanks, good idea, check this branch and let me know what do you think:

https://github.com/marchah/json-mapper-json/tree/add-defaultValue%2316

Also if you don't need any value, you can use `required: false` to don't have an error.

**Comment by xcatliu** [comment]
Looks good!

**Comment by marchah** [comment]
merge and publish into version `1.3.0`
